   import React, { useState } from 'react';
    import ReactDOM from 'react-dom';
    import { Sun, Wind, Droplet, Sprout, ThermometerSun, PanelsTopLeft, Leaf, DollarSign, BatteryCharging, BookOpen, Shield, Image, ChevronDown } from 'lucide-react';

 export   function RenewableEnergySection() {
      const [activeAccordion, setActiveAccordion] = useState(0);

      const facilities = [
        {
          icon: Sun,
          title: 'Solar Energy',
          description: 'Energy harnessed from the sun\'s radiation, primarily using photovoltaic cells or solar thermal systems.',
          color: 'from-blue-500 to-cyan-500'
        },
        {
          icon: Wind,
          title: 'Wind Energy',
          description: 'Captured through wind turbines, this energy source converts kinetic energy from wind into mechanical power.',
          color: 'from-green-500 to-emerald-500'
        },
        {
          icon: Droplet,
          title: 'Hydropower',
          description: 'Generated by converting the energy of flowing water into electricity, usually through dams.',
          color: 'from-orange-500 to-red-500'
        },
        {
          icon: Sprout,
          title: 'Biomass Energy',
          description: 'Created from organic materials which can be burned for heat or converted into biofuels.',
          color: 'from-purple-500 to-pink-500'
        },
        {
          icon: ThermometerSun,
          title: 'Geothermal Energy',
          description: 'Derived from the heat stored beneath the Earth\'s surface, harnessed for electricity generation or direct heating.',
          color: 'from-teal-500 to-cyan-500'
        },
        {
          icon: PanelsTopLeft,
          title: 'System Design and Capacity',
          description: 'The solar power system at the Tagore Institute of Engineering and Technology is designed to produce 50 kW of power. This capacity is sufficient to meet a substantial portion of the institute\'s energy needs, considerably reducing reliance on grid electricity. The solar array installation has been strategically positioned to maximize sunlight exposure throughout the year.',
          color: 'from-yellow-500 to-orange-500'
        },
        {
          icon: Leaf,
          title: 'Environmental Benefits',
          description: 'The switch to solar reduces greenhouse gas emissions significantly, contributing to reduced air pollution and a lower carbon footprint.',
          color: 'from-indigo-500 to-blue-500'
        },
        {
          icon: DollarSign,
          title: 'Cost Savings',
          description: 'While the initial investment in solar technology can be significant, the long-term savings on electricity bills can be substantial. Additionally, in many regions, government incentives can help offset installation costs.',
          color: 'from-rose-500 to-pink-500'
        },
        {
          icon: BatteryCharging,
          title: 'Energy Independence',
          description: 'By generating its own power, the institute reduces its reliance on external energy sources, increasing energy security.',
          color: 'from-blue-500 to-indigo-500'
        },
        {
          icon: BookOpen,
          title: 'Educational Opportunities',
          description: 'The solar installation serves as a practical teaching tool, allowing students to learn about renewable energy technologies and sustainability practices first-hand.',
          color: 'from-green-500 to-teal-500'
        },
        {
          icon: Shield,
          title: 'Resilience',
          description: 'The solar energy system enhances the resilience of campus operations, particularly during grid outages or fluctuations in electricity supply.',
          color: 'from-orange-500 to-yellow-500'
        }
      ];

      const images = [
        {
          src: '/images/facilities/renewable/001.jpg',
          alt: 'Solar Panels',
          caption: 'Solar Panels',
        },
        {
          src: '/images/facilities/renewable/005.jpg',
          alt: 'Wind Turbines',
          caption: 'Wind Turbines',
        },
        {
          src: '/images/facilities/renewable/008.jpg',
          alt: 'Hydropower Dam',
          caption: 'Hydropower Dam',
        },
        {
          src: '/images/facilities/renewable/009.jpg',
          alt: 'Biomass Energy',
          caption: 'Biomass Energy',
        },
      ];

      const toggleAccordion = (index) => {
        setActiveAccordion(activeAccordion === index ? -1 : index);
      };

      return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 relative overflow-hidden pt-5">
          {/* Background Pattern */}
          <div className="absolute inset-0 opacity-5">
            <div className="absolute top-20 left-10 w-72 h-72 bg-blue-400 rounded-full blur-3xl"></div>
            <div className="absolute bottom-20 right-10 w-96 h-96 bg-purple-400 rounded-full blur-3xl"></div>
          </div>

          {/* Hero Section */}
          <div className="text-center space-y-6 mb-10 py-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-50 rounded-full">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm font-medium text-blue-700 uppercase tracking-wide">
                Renewable Energy
              </span>
            </div>
            <p className="text-xl lg:text-2xl font-bold text-gray-900 leading-tight">
              Sustainable energy at
              <span className="block text-blue-600">Tagore Institute Renewable Energy Initiatives</span>
            </p>
          </div>

          {/* Main Content and Accordion */}
          <div className="relative z-10 max-w-7xl mx-auto px-6 pb-20">
            {/* Main Content */}
            <div className="space-y-8 mb-12">
              <div className="space-y-6">
                <h2 className="text-4xl lg:text-5xl font-bold text-gray-900 leading-tight text-center">
                  Tagore Institute
                  <span className="block text-blue-600">Renewable Energy Experience</span>
                </h2>
                <p className="text-lg text-gray-600 leading-relaxed">
                  The growing energy demand and the pressing need to mitigate climate change are driving innovations in renewable energy technologies. The Tagore Institute of Engineering and Technology is dedicated to sustainability and environmental responsibility. As part of this commitment, the institute has implemented a solar power system capable of producing 50 kW of electrical power. This initiative is an illustrative case of how educational institutions can leverage renewable energy sources, particularly solar energy, to not only meet their own energy needs but also educate future generations about sustainability.
                </p>
                <p className="text-lg text-gray-600 leading-relaxed">
                  TIET plans to expand the solar power project further to increase sustainability. This may include integrating smart energy management systems and enhancing energy storage capabilities. Additionally, exploring partnerships with industry experts and other educational institutions can foster innovations in renewable technology.
                </p>
              </div>
            </div>

            {/* Accordion Section */}
            <div className="space-y-4 max-w-4xl mx-auto">
              <div className="text-center mb-8">
                <h3 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
                  Renewable Energy Facilities
                </h3>
                <p className="text-lg text-gray-600">
                  Explore the sustainable energy solutions implemented at TIET.
                </p>
              </div>
              {facilities.map((facility, index) => (
                <div key={index} className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-lg border border-white/20 overflow-hidden">
                  <button
                    onClick={() => toggleAccordion(index)}
                    className="w-full p-6 text-left flex items-center justify-between hover:bg-white/50 transition-all duration-300"
                  >
                    <div className="flex items-center gap-4">
                      <div className={`w-12 h-12 bg-gradient-to-r ${facility.color} rounded-xl flex items-center justify-center shadow-lg`}>
                        <facility.icon className="w-6 h-6 text-white" />
                      </div>
                      <div>
                        <h4 className="text-xl font-bold text-gray-900">{facility.title}</h4>
                      </div>
                    </div>
                    <div className={`transform transition-transform duration-300 ${activeAccordion === index ? 'rotate-180' : ''}`}>
                      <ChevronDown className="w-6 h-6 text-gray-500" />
                    </div>
                  </button>
                  <div className={`overflow-hidden transition-all duration-500 ease-in-out ${
                    activeAccordion === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                  }`}>
                    <div className="px-6 pb-6">
                      <div className="pl-16">
                        <p className="text-gray-600 leading-relaxed text-lg">{facility.description}</p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Image Gallery Section */}
            <div className="bg-blue-50 py-16 mt-16">
              <div className="max-w-7xl mx-auto px-4">
                <div className="flex items-center justify-center mb-8">
                  <Image className="w-8 h-8 text-blue-600 mr-3" />
                  <h2 className="text-3xl font-bold text-gray-900">Renewable Energy Gallery</h2>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
                  {images.map((image, index) => (
                    <div 
                      key={index}
                      className="relative group rounded-lg overflow-hidden shadow-md transform transition-all duration-300 hover:scale-105 hover:shadow-xl"
                    >
                      <img 
                        src={image.src}
                        alt={image.alt}
                        className="w-full h-48 object-cover"
                      />
                      {/* <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-40 transition-opacity duration-300 flex items-center justify-center">
                        <p className="text-white text-lg font-semibold opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                          {image.caption}
                        </p>
                      </div> */}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    }